name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...
    
    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out
        retention-days: 30
    
    - name: Comment test results
      uses: actions/github-script@v7
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        script: |
          const fs = require('fs');
          
          // Read test results from go test output
          const testPassed = process.env.TEST_EXIT_CODE === '0';
          const emoji = testPassed ? '✅' : '❌';
          const status = testPassed ? 'PASSED' : 'FAILED';
          
          const body = `## ${emoji} Test Results for ${context.sha.substring(0, 7)}
          
          **Status**: ${status}
          **Commit**: ${context.sha}
          **Branch**: ${context.ref.replace('refs/heads/', '')}
          **Workflow**: ${context.workflow}
          
          Tests ${testPassed ? 'completed successfully' : 'failed'} on main branch push.
          
          [View full workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId})`;
          
          // Create a commit status
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: testPassed ? 'success' : 'failure',
            description: `Tests ${status}`,
            context: 'ci/tests'
          });
      env:
        TEST_EXIT_CODE: ${{ steps.test.outcome == 'success' && '0' || '1' }}